### ISSUE TITLE
Failure to install Python-sdk with pip

### ISSUE THREAD

**Issue by smetivier** [lambertwang/ctct-python-sdk#1]
I'm trying to install Python-SDK on my Windows 7 machine, using the following command:

pip install constantcontact

and get an error message indicating that the "readme.md" file cannot be found. Everything else seems to be in the constantcontact directory, except this file. Any idea why? (Also noted that the backslashes are duplicated, but figured that was just an output aberration.)

No such file or directory: 'c:\users\steve\appdata\local\temp\pip-build-steve\constantcontact\readme.md'.
I also manually downloaded the tar file from pypl, untarred it, and see that it does not contain the README.MD file.

Is there a way to work around this?

**Comment by lambertwang-zz** [comment]
It seems that I am unable to replicate the results in a virtual environment on windows 10 with both Python 2 and Python 3. I will add readme.md to the source on the pypi and if that does not resolve the issue, could you add more detailed steps as to how you encountered the issue?

**Comment by smetivier** [comment]
Thanks, Lambert. I think that will do it. I was able to install straight
from Github, using this command:

pip install git+https://github.com/magellantoo/ctct-python-sdk

and it seems to be working fine, at least to the point of outputting my
account info.

Thanks for getting back to me.

Cheers,

--Steve
