### ISSUE TITLE
Get Campaigns sent ranked by last_modified

### ISSUE THREAD

**Issue by sam-thecoder** [lambertwang/ctct-python-sdk#6]
I'd like to get campaigns that have been sent ranked by modified date.
Here's the code I use

    `ct = ConstantContact(api_key, access_token)`
    `response = ct.get_campaigns(limit=5, status="SENT")`
    `print json.dumps(response, indent = 4, sort_keys = True)
{
    "meta": {
        "pagination": {
            "next_link": "/v2/emailmarketing/campaigns?next=cGFnZVNpemU9NSZwYWdlTnVtPTYmc3RhdHVzPVNFTlQ"
        }
    }, 
    "results": [
        {
            "id": "1126283301348", 
            "modified_date": "2016-11-02T06:43:12.000Z", 
            "name": "KenyaBuzz Kids Newsletter November 4th - 10th", 
            "status": "SENT"
        }, 
        {
            "id": "1125569998455", 
            "modified_date": "2016-11-01T20:39:29.000Z", 
            "name": "AutoXpress 32nd Branch Opening Sale!", 
            "status": "SENT"
        }, 
        {
            "id": "1125352500441", 
            "modified_date": "2016-11-01T20:39:29.000Z", 
            "name": "Fedha Residences Kenya", 
            "status": "SENT"
        }, 
        {
            "id": "1125327064220", 
            "modified_date": "2016-11-01T20:39:29.000Z", 
            "name": "KenyaBuzz Kids Newsletter July 22nd - 28th", 
            "status": "SENT"
        }, 
        {
            "id": "1125159797871", 
            "modified_date": "2016-11-01T20:39:29.000Z", 
            "name": "Movies Newsletter - July 1st - 7th", 
            "status": "SENT"
        }
    ]
}`

Snapshot of the order attached shows there's an issue with this, there's newsletters from july in the top 5 recent.

![a](https://cloud.githubusercontent.com/assets/15666437/19957761/a2a0b55a-a1aa-11e6-9288-2ef31c4d777c.png)
![b](https://cloud.githubusercontent.com/assets/15666437/19957772/b3a59df2-a1aa-11e6-9313-aa9df825c9a9.png)

**Comment by lambertwang-zz** [comment]
Sorry for the late reply.

According to the CTCT API Documentation [here](https://developer.constantcontact.com/docs/email-campaigns/email-campaigns-collection.html) the campaign sort order is dependent on the campaign status. Through the API, you cannot get SENT emails sorted by modified date.  It is very easy to get sent emails sorted by send date and draft emails sorted by modified date. I don't know if there is an easy way to get sent emails sorted by modified date besides retrieving all of your sent emails and sorting them by modified but I don't know if that's efficient.

**Comment by lambertwang-zz** [comment]
Closing issue as stale
